source 'https://rubygems.org'

ruby '2.4.1'

gem 'activemodel', '~> 5.1', require: 'active_model'
gem 'activerecord', '~> 5.1', require: 'active_record'
gem 'activesupport', '~> 5.1', require: 'active_support'
gem 'bunny', '~> 2.7'
gem 'pg', '~> 0.21'
gem 'rake', require: false

